fix: fix column missing issue for jsonl record schema when reading json/jsonl files (#5681)
## Issue

```
daft.read_json('/mnt/test/vedio.audio-00002.jsonl').where(
    "sound is null"
).count_rows()
```

```
ray.exceptions.RayTaskError(DaftCoreException): ray::PhysicalScan->UnGroupedAggregate->Project() (pid=xx, ip=xx.xx.xx.xx, actor_id=xxxx, repr=<daft.runners.flotilla.RaySwordfishActor object at xxxxxxx>)
daft.exceptions.DaftCoreException: DaftError::FieldNotFound Column "sound" not found in schema: [Field { name: "video_meta", dtype: Struct([Field { name: "target_fps", dtype: Int64, metadata: {} }]), metadata: {} }]

```

## Changes Made

When reading large JSONL files with automatic schema inference enabled,
only the first 1M are used by default to infer the schema. In cases
where the data is very sparse, some columns may be missing from the
inferred schema. If users later attempt to access such missing columns,
an error occurs.

The purpose of this change is to eliminate the need for users to
manually provide a large and complete schema in sparse-column scenarios.
By enhancing the semantics of schema hints to support an "`add-missing`"
behavior, the system can automatically add any missing columns to the
final schema when they are accessed. This reduces complexity and
improves ease of use.

<!-- Describe what changes were made and why. Include implementation
details if necessary. -->

## Related Issues

https://github.com/Eventual-Inc/Daft/issues/5647

<!-- Link to related GitHub issues, e.g., "Closes #123" -->

## How to test
new UTs.